#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# check current branch is main branch
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "You can't commit directly to master/main branch"
  exit 1
fi

# test & lint
npm run lint-staged
